services:
  wukond:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - db_data:/app/instance
      - db_data:/app/uploads

volumes:
  db_data:
